### ISSUE TITLE
Implement a better CSV parser

### ISSUE THREAD

**Issue by keichi** [keichi/cuEDM#16]
We need to find or implement a better CSV parser. Our current CSV parser impelemented in `Dataset` can't handle spaces after a comma. It's internally using `std::stof()`, which is not very fast. The new CSV parser should be able to parse:

1. Parse faster than our current parser
1. Handle at least 20,000 rows
2. Handle at least 53,000 columns
3. Parse without knowing the numbers of columns in advance

https://github.com/vincentlaucsb/csv-parser doesn't satisfy 2 and https://github.com/ben-strasser/fast-cpp-csv-parser doesn't satisfy 3 (not entirely sure). 

We should also consider switching to a binary format such as HDF5.

**Comment by KoheiIchikawa** [comment]
How about using boost::tokenizer?

**Comment by keichi** [comment]
I was trying to avoid boost since it's such a huge library and I don't want to bloat the dependencies. Is boost::tokenizer fast?

**Comment by KoheiIchikawa** [comment]
I think boost libraries are well optimized and fast. Of course, it's slower than just calling std::getline.
I like boost. It has been developed by many people, and has long life.

**Comment by keichi** [comment]
Let me think about this (and benchmark). I completely agree boost is mature, but I don't want to link boost just for parsing CSV files.

**Comment by KoheiIchikawa** [comment]
In my environment, parsing 60,000 columns data by std::getline takes about 3.0ms.
Parsing the same data by tokenizer taks 4.2ms.

**Comment by keichi** [comment]
I decided not to pursue this direction and go with HDF5... I don't think we should optimize for humongous CSV files with 50,000 columns. HDF5 has a mature ecosystem and already supported by pandas, numpy, etc. Most importantly, the read performance is an order of magnitude higher:

Fish1_150a_Normo.csv 39.5 [ms]
Fish1_150a_Normo.h5 2.1 [ms] (19x faster than CSV)

Trace_Normo_133105.csv 11421.8 [ms]
Trace_Normo_133105.h5 394.772 [ms] (29x faster than CSV)
