### ISSUE TITLE
Investigate mysterious SGE error on ITC cluster

### ISSUE THREAD

**Issue by keichi** [keichi/cuEDM#17]
The jobs @boom10899 is running on ITC occasionally hang with the following mysterious error:
```
execution daemon on host XXX didn't accept task
```
Is this a problem with our application or a problem in SGE? 
https://stackoverflow.com/questions/14775451/submitting-open-mpi-jobs-to-sge

**Comment by boom10899** [comment]
From previous job script, the script wrote the host name into "host.txt". When we submitted multi job into the queue, every job will write the host list into the same file that make other jobs access the unauthorized hosts. We solved the problem with generate a temporary file for writing the host list.

```
#$ -S /bin/bash
#$ -q grid_short.q
#$ -pe mpi 792

module load compiler/intel/2018/1.038
module load mpi/intel/2018

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/parallel_studio_xe/itac/2018.1.017/intel64/slib/libVT.so

HOST=`mktemp`
cut -d ' ' -f 1 $PE_HOSTFILE > $HOST

echo "========== Allocated hosts:"
mpirun -hostfile $HOST -ppn 1 -n 33 hostname

echo "========== Trace_Normo_133105.csv"
mpirun -trace -hostfile $HOST -ppn 1 -n 33 ./cuEDM/build/simplex_mpi_bench data/Trace_Normo_133105.csv
echo "=========="

rm -f $HOST
```
